"""Render a workout session to HTML and send it via Gmail SMTP.

A session now carries one proposal per model (Nemotron, DeepSeek). The email
renders them side by side so the athlete can compare and pick, with a link to
the feedback web app to log which one they preferred and how it felt.

Uses a Gmail App Password (16 chars), NOT the account password — Google blocks
basic auth otherwise. Port 587 + STARTTLS.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .exercise_links import get_url


def _variants(session):
    """Normalize to a list of (model_label, workout). Tolerates a bare workout."""
    if session.get("variants"):
        return [(v.get("model", "Model"), v.get("workout", {})) for v in session["variants"]]
    return [(session.get("model", ""), session)]


def _table(workout: dict) -> str:
    blocks_html = ""
    for block in workout.get("blocks", []):
        rows = ""
        for ex in block.get("exercises", []):
            name = ex.get("name", "")
            url = get_url(name)
            linked_name = f'<a href="{url}" style="color:#1a5;text-decoration:none;">{name} ▶</a>'
            rows += f"""
              <tr>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;">{linked_name}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('sets','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('reps','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;">{ex.get('load','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('rpe','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#555;font-size:13px;">{ex.get('notes','')}</td>
              </tr>"""
        blocks_html += f"""
          <h4 style="margin:18px 0 6px;color:#1a5">{block.get('name','')}</h4>
          <table style="border-collapse:collapse;width:100%;font-size:14px;">
            <tr style="background:#f4f4f4;text-align:left;">
              <th style="padding:6px 10px;">Exercise</th>
              <th style="padding:6px 10px;">Sets</th>
              <th style="padding:6px 10px;">Reps</th>
              <th style="padding:6px 10px;">Load</th>
              <th style="padding:6px 10px;">RPE</th>
              <th style="padding:6px 10px;">Notes</th>
            </tr>
            {rows}
          </table>"""
    return blocks_html


def render_html(session: dict) -> str:
    day = session.get("day", "").title()
    deload = " · DELOAD WEEK" if session.get("deload") else ""
    variants = _variants(session)
    web_url = os.environ.get("WEB_URL", "").rstrip("/")

    sections = ""
    for label, workout in variants:
        focus = workout.get("focus", "")
        notes = workout.get("coach_notes", "")
        source = workout.get("source", "")
        header = label or source or "Workout"
        sections += f"""
          <div style="margin-top:26px;padding-top:8px;border-top:3px solid #1a5;">
            <h3 style="margin:6px 0 0;">{header}</h3>
            <p style="margin:2px 0 0;color:#666;">{focus}</p>
            {_table(workout)}
            <div style="margin-top:14px;padding:10px 12px;background:#f0f7f0;border-left:4px solid #1a5;border-radius:4px;">
              <strong>Coach notes:</strong> {notes}
            </div>
          </div>"""

    compare_hint = (
        "<p style='color:#666;'>Two coaches designed today's session independently — "
        "pick the one you like, or mix and match.</p>"
        if len(variants) > 1 else ""
    )

    feedback_cta = ""
    if web_url:
        feedback_cta = f"""
          <div style="margin-top:26px;text-align:center;">
            <a href="{web_url}" style="display:inline-block;padding:12px 22px;background:#1a5;color:#fff;
               text-decoration:none;border-radius:6px;font-weight:600;">
              Log how it went ▸
            </a>
            <p style="margin-top:8px;color:#999;font-size:12px;">
              Rate the session, say which coach you preferred, leave notes — it feeds back into next time.
            </p>
          </div>"""

    return f"""<html><body style="font-family:-apple-system,Segoe UI,Arial,sans-serif;max-width:760px;margin:0 auto;color:#222;">
      <h2 style="margin-bottom:0;">{day} Strength{deload}</h2>
      {compare_hint}
      {sections}
      {feedback_cta}
      <p style="margin-top:22px;color:#999;font-size:12px;">
        Generated by coach_claude. Stop any shoulder movement that pinches.
      </p>
    </body></html>"""


def send(session: dict):
    user = os.environ["GMAIL_ADDRESS"]
    app_pw = os.environ["GMAIL_APP_PASSWORD"]
    to = os.environ.get("EMAIL_TO", user)

    day = session.get("day", "").title()
    deload = " (deload)" if session.get("deload") else ""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{day} Strength{deload} — coach_claude"
    msg["From"] = user
    msg["To"] = to
    msg.attach(MIMEText(render_html(session), "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(user, app_pw)
        server.sendmail(user, [to], msg.as_string())
