"""Render a workout to HTML and send it via Gmail SMTP.

Uses a Gmail App Password (16 chars), NOT the account password — Google blocks
basic auth otherwise. Port 587 + STARTTLS.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .exercise_links import get_url


def render_html(workout: dict) -> str:
    day = workout.get("day", "").title()
    focus = workout.get("focus", "")
    deload = " · DELOAD WEEK" if workout.get("deload") else ""
    source = workout.get("source", "")
    notes = workout.get("coach_notes", "")

    blocks_html = ""
    for block in workout.get("blocks", []):
        rows = ""
        for ex in block.get("exercises", []):
            name = ex.get('name', '')
            url = get_url(name)
            linked_name = f'<a href="{url}" style="color:#1a5;text-decoration:none;">{name} ▶</a>'
            rows += f"""
              <tr>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;">{linked_name}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('sets','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('reps','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;">{ex.get('load','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:center;">{ex.get('rpe','')}</td>
                <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#555;font-size:13px;">{ex.get('notes','')}</td>
              </tr>"""
        blocks_html += f"""
          <h3 style="margin:22px 0 6px;color:#1a5">{block.get('name','')}</h3>
          <table style="border-collapse:collapse;width:100%;font-size:14px;">
            <tr style="background:#f4f4f4;text-align:left;">
              <th style="padding:6px 10px;">Exercise</th>
              <th style="padding:6px 10px;">Sets</th>
              <th style="padding:6px 10px;">Reps</th>
              <th style="padding:6px 10px;">Load</th>
              <th style="padding:6px 10px;">RPE</th>
              <th style="padding:6px 10px;">Notes</th>
            </tr>
            {rows}
          </table>"""

    return f"""<html><body style="font-family:-apple-system,Segoe UI,Arial,sans-serif;max-width:720px;margin:0 auto;color:#222;">
      <h2 style="margin-bottom:0;">{day} Strength{deload}</h2>
      <p style="margin-top:4px;color:#666;">{focus}</p>
      {blocks_html}
      <div style="margin-top:24px;padding:12px 14px;background:#f0f7f0;border-left:4px solid #1a5;border-radius:4px;">
        <strong>Coach notes:</strong> {notes}
      </div>
      <p style="margin-top:18px;color:#999;font-size:12px;">
        Generated by coach_claude ({source}). Stop any shoulder movement that pinches.
      </p>
    </body></html>"""


def send(workout: dict):
    user = os.environ["GMAIL_ADDRESS"]
    app_pw = os.environ["GMAIL_APP_PASSWORD"]
    to = os.environ.get("EMAIL_TO", user)

    day = workout.get("day", "").title()
    deload = " (deload)" if workout.get("deload") else ""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{day} Strength{deload} — coach_claude"
    msg["From"] = user
    msg["To"] = to
    msg.attach(MIMEText(render_html(workout), "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(user, app_pw)
        server.sendmail(user, [to], msg.as_string())
